version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "order-service"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"